#MTR Traffic Addon config
#Fri Oct 09 11:42:52 CEST 2026
trafficVehicleMaterializationMarginChunks=2
trafficVehicleSimulationDistanceBlocks=auto
trafficVehicleUnrenderedLifetimeSeconds=30
trafficVehicleVisibilityDistanceBlocks=auto
